"""init table

Revision ID: 3667ec7b8326
Revises: 
Create Date: 2023-06-25 22:44:12.889042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3667ec7b8326'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='category name'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='category name'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='create time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'name', name='unix_id_name')
    )
    op.create_table('movie',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='movie name'),
    sa.Column('other_names', sa.Text(), nullable=False, comment='other movie names'),
    sa.Column('source', sa.String(length=1024), nullable=False, comment='url'),
    sa.Column('source_hash', sa.String(length=32), nullable=False, comment='shorter url'),
    sa.Column('release_year', sa.SmallInteger(), nullable=False, comment='year'),
    sa.Column('release_date', sa.Text(), nullable=False, comment='release date'),
    sa.Column('production_country', sa.String(length=1024), nullable=False, comment='country'),
    sa.Column('language', sa.String(length=1024), nullable=False, comment='main language'),
    sa.Column('languages', sa.String(length=1024), nullable=False, comment='other languages'),
    sa.Column('video_length', sa.BigInteger(), nullable=False, comment='movie length(in seconds)'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='movie length(in seconds)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash', name='uniq_idx_source_hash')
    )
    op.create_index('idx_name_releaseyear_id', 'movie', ['name', 'release_year', 'id'], unique=False)
    op.create_table('movie_link',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('movie_id', sa.BigInteger(), nullable=False, comment='movie id'),
    sa.Column('link', sa.Text(), nullable=False, comment='download url'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movieid', 'movie_link', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_movieid', table_name='movie_link')
    op.drop_table('movie_link')
    op.drop_index('idx_name_releaseyear_id', table_name='movie')
    op.drop_table('movie')
    op.drop_table('category')
    # ### end Alembic commands ###
