"""change production country to longer text

Revision ID: 4ba056bc9669
Revises: 70e4e79c545d
Create Date: 2023-06-27 01:21:11.248875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ba056bc9669'
down_revision = '70e4e79c545d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'production_country',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               type_=sa.Text(),
               existing_comment='country',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'production_country',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               existing_comment='country',
               existing_nullable=False)
    # ### end Alembic commands ###
