"""change production country to longer text

Revision ID: 70e4e79c545d
Revises: 893a7e075a03
Create Date: 2023-06-27 01:16:45.246035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e4e79c545d'
down_revision = '893a7e075a03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
