"""added mirroring of category and movie id

Revision ID: b756f55c9ce3
Revises: 4ba056bc9669
Create Date: 2023-06-27 02:36:21.987435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b756f55c9ce3'
down_revision = '4ba056bc9669'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_movie',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='category name'),
    sa.Column('category_name', sa.String(length=32), nullable=False, comment='category name'),
    sa.Column('movie_id', sa.BigInteger(), nullable=False, comment='movie id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name', 'movie_id', name='uniq_idx_name_id')
    )
    op.create_index('idx_category_movie', 'category_movie', ['movie_id', 'category_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_category_movie', table_name='category_movie')
    op.drop_table('category_movie')
    # ### end Alembic commands ###
